### ISSUE TITLE
Frontend workflow is not triggered by dependabot PR

### ISSUE THREAD

**Issue by thomass-dev** [probabl-ai/skore#386]
In https://github.com/probabl-ai/skore/pull/384 , the frontend PR wasn't triggered by dependabot PR, which is weird.
Maybe add "opened" in the constraint of the workflow ?

```yaml
on:                                   
  pull_request:                       
    types: [synchronize]   # [synchronize, opened] ?           
    paths:                            
      - 'frontend/**'                 
      - Makefile                      
      - .github/workflows/frontend.yml
```

Take a look at https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
