### ISSUE TITLE
bug: `skore.show_versions()` does not show `scikit-learn`'s version

### ISSUE THREAD

**Issue by tuscland** [probabl-ai/skore#987]
When running `skore.show_versions()`, the result is:

```
System:
    python: 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 15.0.0 (clang-1500.3.9.4)]
executable: /Users/camille/Hacque/probabl/internal_demos/.direnv/python-3.12/bin/python
   machine: macOS-15.2-arm64-arm-64bit

Python dependencies:
        skore: 0.5.0
          pip: 24.2
   setuptools: None
    diskcache: 5.6.3
      fastapi: 0.115.6
 plotly<6,>=5: None
      pyarrow: 18.1.0
         rich: 13.9.4
scikit-learn<1.7: None
        skops: 0.11.0
      uvicorn: 0.34.0
```

Since we are controlling the upper bound version for `scikit-learn`, the procedure fails to parse the actual version number.  
Same goes for plotly, no version is displayed.
